application: psa-dna-netbooster
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /export/launch
  script: export.app
  login: admin
- url: /export/check
  script: export.app
  login: admin
